#include "explorer.h"

static char const *const css[] = {
	":root{--bg:#f6f7f9;--card:#fff;--ink:#1d2330;",
	"--muted:#6b7280;--line:#e3e6ea;--accent:#2f6fde;",
	"--ok:#1f9d55;--bad:#d64545}",
	"@media (prefers-color-scheme:dark){:root{--bg:#12151b;",
	"--card:#1b2029;--ink:#e6e9ef;--muted:#9aa3b2;",
	"--line:#2b313c;--accent:#6ea0ff;--ok:#3ecf8e;--bad:#ff6b6b}}",
	"*{box-sizing:border-box}",
	"body{margin:0;background:var(--bg);color:var(--ink);",
	"font:15px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}",
	"header,main,footer{max-width:960px;margin:0 auto;padding:16px}",
	"h1{margin:8px 0 0}h2{margin:0 0 4px;font-size:18px}",
	"h3{font-size:15px;margin:12px 0 4px}",
	"h4{margin:4px 0;font-size:13px;color:var(--muted)}",
	".muted{color:var(--muted)}a{color:var(--accent)}",
	".mono{font-family:ui-monospace,Menlo,Consolas,monospace;",
	"font-size:13px;word-break:break-all}",
	".stats{display:grid;gap:12px;margin:0 0 16px;",
	"grid-template-columns:repeat(auto-fit,minmax(150px,1fr))}",
	".stat,.block,table{background:var(--card);",
	"border:1px solid var(--line);border-radius:10px}",
	".stat{padding:12px}.stat b{display:block;font-size:22px}",
	".block{border-left:4px solid var(--ok);padding:16px}",
	".block.bad{border-left-color:var(--bad)}",
	".badge{font-size:12px;padding:2px 8px;border-radius:99px;",
	"background:var(--ok);color:#fff;vertical-align:middle}",
	".bad .badge,.warn{background:var(--bad);color:#fff}",
	".warn{padding:10px 14px;border-radius:8px;margin:0 0 16px}",
	".link{text-align:center;color:var(--muted);margin:6px 0}",
	"dl{display:grid;grid-template-columns:110px 1fr;",
	"gap:4px 12px;margin:8px 0}dt{color:var(--muted)}dd{margin:0}",
	".tx{border:1px solid var(--line);border-radius:8px;",
	"padding:10px;margin:8px 0}",
	".io{display:grid;grid-template-columns:1fr 1fr;gap:12px}",
	".io p{margin:2px 0}.scroll{overflow-x:auto}",
	".tag{background:var(--accent);color:#fff;border-radius:4px;",
	"padding:1px 6px;font-size:12px}",
	"table{width:100%;border-collapse:collapse}",
	"th,td{text-align:left;padding:6px 10px;",
	"border-bottom:1px solid var(--line)}",
	"@media (max-width:600px){.io,dl{grid-template-columns:1fr}}",
	NULL
};

/**
 * html_head - writes the page head, styles and header
 *
 * @fp:     output stream
 * @source: path of the loaded Blockchain file
 */
void html_head(FILE *fp, char const *source)
{
	size_t i;

	fprintf(fp, "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
	fprintf(fp, "<meta charset=\"utf-8\">\n<meta name=\"viewport\" ");
	fprintf(fp, "content=\"width=device-width, initial-scale=1\">\n");
	fprintf(fp, "<title>Blockchain Explorer</title>\n<style>\n");
	for (i = 0; css[i]; i++)
		fprintf(fp, "%s\n", css[i]);
	fprintf(fp, "</style>\n</head>\n<body>\n<header>\n");
	fprintf(fp, "<h1>Blockchain Explorer</h1>\n");
	fprintf(fp, "<p class=\"muted\">Source: ");
	html_text(fp, (int8_t const *)source, strlen(source));
	fprintf(fp, "</p>\n</header>\n<main>\n");
}

/**
 * html_foot - writes the page footer and closes the document
 *
 * @fp: output stream
 */
void html_foot(FILE *fp)
{
	fprintf(fp, "</main>\n<footer class=\"muted\">Generated by ");
	fprintf(fp, "hblk_explorer &middot; HBLK format %s</footer>\n",
		HBLK_VERSION);
	fprintf(fp, "</body>\n</html>\n");
}

/**
 * html_stat - writes one summary card
 *
 * @fp:    output stream
 * @label: card label
 * @value: card value
 */
static void html_stat(FILE *fp, char const *label, unsigned long value)
{
	fprintf(fp, "<div class=\"stat\"><b>%lu</b>", value);
	fprintf(fp, "<span class=\"muted\">%s</span></div>\n", label);
}

/**
 * html_summary - writes the summary cards and integrity warning
 *
 * @fp:       output stream
 * @bc:       Blockchain
 * @nb_valid: number of Blocks that passed the audit
 */
void html_summary(FILE *fp, blockchain_t const *bc, int nb_valid)
{
	int i, size = llist_size(bc->chain), nb_unspent, n;
	unsigned long nb_tx = 0, supply = 0;
	block_t *block;
	unspent_tx_out_t *u;

	for (i = 0; i < size; i++)
	{
		block = llist_get_node_at(bc->chain, i);
		n = llist_size(block->transactions);
		nb_tx += n > 0 ? n : 0;
	}
	nb_unspent = llist_size(bc->unspent);
	for (i = 0; i < nb_unspent; i++)
	{
		u = llist_get_node_at(bc->unspent, i);
		supply += u->out.amount;
	}
	fprintf(fp, "<div class=\"stats\">\n");
	html_stat(fp, "Blocks", size);
	html_stat(fp, "Valid blocks", nb_valid);
	html_stat(fp, "Transactions", nb_tx);
	html_stat(fp, "Unspent outputs", nb_unspent > 0 ? nb_unspent : 0);
	html_stat(fp, "Coins in circulation", supply);
	fprintf(fp, "</div>\n");
	if (nb_valid != size)
		fprintf(fp, "<div class=\"warn\">Integrity check failed: "
			"%d of %d blocks are invalid.</div>\n",
			size - nb_valid, size);
}
